// This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © Trendoscope Pty Ltd, Trendoscope®
//                                       ░▒
//                                  ▒▒▒   ▒▒
//                              ▒▒▒▒▒     ▒▒
//                      ▒▒▒▒▒▒▒░     ▒     ▒▒
//                  ▒▒▒▒▒▒           ▒     ▒▒
//             ▓▒▒▒       ▒        ▒▒▒▒▒▒▒▒▒▒▒
//   ▒▒▒▒▒▒▒▒▒▒▒ ▒        ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
//   ▒  ▒       ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░
//   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒
//   ▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒
//    ▒▒▒▒▒         ▒▒▒▒▒▒▒
//                 ▒▒▒▒▒▒▒▒▒
//                ▒▒▒▒▒ ▒▒▒▒▒
//               ░▒▒▒▒   ▒▒▒▒▓      ████████╗██████╗ ███████╗███╗   ██╗██████╗  ██████╗ ███████╗ ██████╗ ██████╗ ██████╗ ███████╗
//              ▓▒▒▒▒     ▒▒▒▒      ╚══██╔══╝██╔══██╗██╔════╝████╗  ██║██╔══██╗██╔═══██╗██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔════╝
//              ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒        ██║   ██████╔╝█████╗  ██╔██╗ ██║██║  ██║██║   ██║███████╗██║     ██║   ██║██████╔╝█████╗
//             ▒▒▒▒▒       ▒▒▒▒▒       ██║   ██╔══██╗██╔══╝  ██║╚██╗██║██║  ██║██║   ██║╚════██║██║     ██║   ██║██╔═══╝ ██╔══╝
//            ▒▒▒▒▒         ▒▒▒▒▒      ██║   ██║  ██║███████╗██║ ╚████║██████╔╝╚██████╔╝███████║╚██████╗╚██████╔╝██║     ███████╗
//             ▒▒             ▒
//@version=6

// @description Library having OHLC and Indicator type and method implementations.
library('ohlc', overlay = true)

// @type Object containing Indicator name and value
// @field name Indicator Name
// @field value Indicator Value as a chart point
export type Indicator
	string name
	chart.point value

// @type Object containing OHLC and indicator values
// @field o Open price
// @field h High Price
// @field l Low Price
// @field c Close Price
// @field highBeforeLow to be calculated based on lower timeframe. high price attained within the candle before reaching the lowest point.
// @field highAfterLow to be calculated based on lower timeframe. high price attained within the candle after reaching the lowest point.
// @field lowBeforeHigh to be calculated based on lower timeframe. low price attained within the candle before reaching the highest point.
// @field lowAfterHigh to be calculated based on lower timeframe. low price attained within the candle after reaching the highest point.
// @field barindex bar_index of OHLC data
// @field bartime time of OHLC cata
// @field indicators array containing indicator
export type OHLC
	float o = open
	float h = high
	float l = low
	float c = close
	float highBeforeLow = high
	float highAfterLow = high
	float lowBeforeHigh = low
	float lowAfterHigh = low
	int barindex = bar_index
	int bartime = time
	array<Indicator> indicators

// @function get array of OHLC values when called on every bar
// @param o Open price
// @param h High Price
// @param l Low Price
// @param c Close Price
// @param highBeforeLow to be calculated based on lower timeframe. high price attained within the candle before reaching the lowest point.
// @param highAfterLow to be calculated based on lower timeframe. high price attained within the candle after reaching the lowest point.
// @param lowBeforeHigh to be calculated based on lower timeframe. low price attained within the candle before reaching the highest point.
// @param lowAfterHigh to be calculated based on lower timeframe. low price attained within the candle after reaching the highest point.
// @param barindex bar_index of OHLC data
// @param bartime time of OHLC cata
// @param indicators array containing indicator
// @returns Array of OHLC objects
export getOhlcArray(float o = open, float h = high, float l = low, float c = close, float highBeforeLow = high, float highAfterLow = high, float lowBeforeHigh = low, float lowAfterHigh = low, int barindex = bar_index, int bartime = time, array<Indicator> indicators = na) =>
    var array<OHLC> ohlcArray = array.new<OHLC>()
    ohlcArray.push(OHLC.new(o, h, l, c, highBeforeLow, highAfterLow, lowBeforeHigh, lowAfterHigh, barindex, bartime, indicators))
    ohlcArray

// @function Push items to OHLC array with maxItems limit
// @param item OHLC Item to be pushed to the array
// @param maxItems max Items the array can hold at a time
// @returns current object
export push(array<OHLC> this, OHLC item, int maxItems = 10) =>
    this.push(item)
    while this.size() > maxItems
        this.shift()
    this

// @function Unshift items to OHLC array with maxItems limit
// @param item OHLC Item to be unshifted to the array
// @param maxItems max Items the array can hold at a time
// @returns current object
export unshift(array<OHLC> this, OHLC item, int maxItems = 10) =>
    this.unshift(item)
    while this.size() > maxItems
        this.pop()
    this

// @function Push items to Indicator array with maxItems limit
// @param item Indicator Item to be pushed to the array
// @param maxItems max Items the array can hold at a time
// @returns current object
export push(array<Indicator> this, Indicator item, int maxItems = 10) =>
    this.push(item)
    while this.size() > maxItems
        this.shift()
    this

// @function Unshift items to Indicator array with maxItems limit
// @param item Indicator Item to be unshifted to the array
// @param maxItems max Items the array can hold at a time
// @returns current object
export unshift(array<Indicator> this, Indicator item, int maxItems = 10) =>
    this.unshift(item)
    while this.size() > maxItems
        this.pop()
    this

// @function get array of points based on array of indicator values
// @param indicators Array containing indicator objects
// @param maxItems max Items the array can hold at a time
// @returns array of indicator points
export method getPoints(array<Indicator> indicators) =>
    points = array.new<chart.point>()
    for indicator in indicators
        points.push(indicator.value)
    points

// @function plots an array of Indicator using polyline
// @param indicator Array containing indicator objects
// @param xloc can have values xloc.bar_index or xloc.bar_time. Used for drawing the line based on either bars or time.
// @param line_color color in which the plots need to be printed on chart.
// @param line_style line style line.style_solid, line.style_dotted, line.style_dashed, line.style_arrow_right, line.style_arrow_left, line.style_arrow_both
// @param line_width width of the plot line
// @returns array of plot polyline
export method plot(array<Indicator> indicator, string xloc = xloc.bar_index, color line_color = color.blue, string line_style = line.style_solid, int line_width = 1) =>
    var array<polyline> plots = array.new<polyline>()
    for l in plots
        l.delete()

    points = indicator.getPoints()
    for i = 1 to math.ceil(points.size() / 10000) by 1
        slice = points.slice((i - 1) * 10000, math.min(i * 10000, points.size()))
        l = polyline.new(slice, true, false, xloc, line_color, line_style = line_style, line_width = line_width)
        plots.push(l)
    plots

// Example program
// var array<Indicator> indicator = array.new<Indicator>()
// indicatorValue = ta.rsi(close, 14)
// indicator.push(Indicator.new("RSI", chart.point.now(indicatorValue)))
// indicator.plot()
