// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Trendoscope Pty Ltd, Trendoscope®
//                                       ░▒
//                                  ▒▒▒   ▒▒
//                              ▒▒▒▒▒     ▒▒
//                      ▒▒▒▒▒▒▒░     ▒     ▒▒
//                  ▒▒▒▒▒▒           ▒     ▒▒
//             ▓▒▒▒       ▒        ▒▒▒▒▒▒▒▒▒▒▒
//   ▒▒▒▒▒▒▒▒▒▒▒ ▒        ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
//   ▒  ▒       ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░
//   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒
//   ▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒
//    ▒▒▒▒▒         ▒▒▒▒▒▒▒
//                 ▒▒▒▒▒▒▒▒▒
//                ▒▒▒▒▒ ▒▒▒▒▒
//               ░▒▒▒▒   ▒▒▒▒▓      ████████╗██████╗ ███████╗███╗   ██╗██████╗  ██████╗ ███████╗ ██████╗ ██████╗ ██████╗ ███████╗
//              ▓▒▒▒▒     ▒▒▒▒      ╚══██╔══╝██╔══██╗██╔════╝████╗  ██║██╔══██╗██╔═══██╗██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔════╝
//              ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒        ██║   ██████╔╝█████╗  ██╔██╗ ██║██║  ██║██║   ██║███████╗██║     ██║   ██║██████╔╝█████╗
//             ▒▒▒▒▒       ▒▒▒▒▒       ██║   ██╔══██╗██╔══╝  ██║╚██╗██║██║  ██║██║   ██║╚════██║██║     ██║   ██║██╔═══╝ ██╔══╝
//            ▒▒▒▒▒         ▒▒▒▒▒      ██║   ██║  ██║███████╗██║ ╚████║██████╔╝╚██████╔╝███████║╚██████╗╚██████╔╝██║     ███████╗
//             ▒▒             ▒
//@version=6
// QTSS reference: TradingView `Trendoscope/LineWrapper/2`. `get_price` matches Rust `line_price_at_bar_index`
// (`crates/qtss-chart-patterns/src/lib.rs`) and web `linePriceAtBarIndex` in `patternDrawingBatchOverlay.ts`.

// @description Wrapper Type for Line. Useful when you want to store the line details without drawing them. Can also be used in scenarios where you collect lines to be drawn and draw together towards the end.
library('LineWrapper', overlay = true)

// @type Line Wrapper object
// @field xloc (series string) See description of x1 argument. Possible values: xloc.bar_index and xloc.bar_time. Default is xloc.bar_index.
// @field extend (series string) If extend=extend.none, draws segment starting at point (x1, y1) and ending at point (x2, y2). If extend is equal to extend.right or extend.left, draws a ray starting at point (x1, y1) or (x2, y2), respectively. If extend=extend.both, draws a straight line that goes through these points. Default value is extend.none.
// @field color (series color) Line color.
// @field style (series string) Line style. Possible values: line.style_solid, line.style_dotted, line.style_dashed, line.style_arrow_left, line.style_arrow_right, line.style_arrow_both.
// @field width (series int) Line width in pixels.
// @field obj line object
export type Line
	chart.point p1
	chart.point p2
	string xloc = xloc.bar_index
	string extend = extend.none
	color color = color.blue
	string style = line.style_solid
	int width = 1
	line obj = na

// @function draws line as per the wrapper object contents
// @param this (series Line) Line object.
// @returns current Line object
export method draw(Line this) =>
    if not na(this.p1) and not na(this.p2)
        this.obj.delete()
        this.obj := line.new(this.p1, this.p2, this.xloc, this.extend, this.color, this.style, this.width)
        this.obj
    this

// @function draws lines as per the wrapper object array
// @param this (series array<Line>) Array of Line object.
// @returns current Array of Line objects
export method draw(array<Line> this) =>
    for ln in this
        ln.draw()
    this

// @function updates or redraws line as per the wrapper object contents
// @param this (series Line) Line object.
// @returns current Line object
export method update(Line this) =>
    this.obj.delete()
    this.draw()
    this

// @function updates or redraws lines as per the wrapper object array
// @param this (series array<Line>) Array of Line object.
// @returns current Array of Line objects
export method update(array<Line> this) =>
    for ln in this
        ln.update()
    this

// @function Deletes the underlying line drawing object
// @param this (series Line) Line object.
// @returns Current Line object
export method delete(Line this) =>
    this.obj.delete()
    this

// @function get line price based on bar
// @param this (series Line) Line object.
// @param bar bar index at which line price should be calculated
// @returns line price at given bar.
export method get_price(Line this, int bar) =>
    stepPerBar = (this.p2.price - this.p1.price) / (this.p2.index - this.p1.index)
    distance = bar - this.p1.index
    this.p1.price + distance * stepPerBar
