// This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © Trendoscope Pty Ltd, Trendoscope®
//                                       ░▒
//                                  ▒▒▒   ▒▒
//                              ▒▒▒▒▒     ▒▒
//                      ▒▒▒▒▒▒▒░     ▒     ▒▒
//                  ▒▒▒▒▒▒           ▒     ▒▒
//             ▓▒▒▒       ▒        ▒▒▒▒▒▒▒▒▒▒▒
//   ▒▒▒▒▒▒▒▒▒▒▒ ▒        ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
//   ▒  ▒       ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░
//   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒
//   ▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒
//    ▒▒▒▒▒         ▒▒▒▒▒▒▒
//                 ▒▒▒▒▒▒▒▒▒
//                ▒▒▒▒▒ ▒▒▒▒▒
//               ░▒▒▒▒   ▒▒▒▒▓      ████████╗██████╗ ███████╗███╗   ██╗██████╗  ██████╗ ███████╗ ██████╗ ██████╗ ██████╗ ███████╗
//              ▓▒▒▒▒     ▒▒▒▒      ╚══██╔══╝██╔══██╗██╔════╝████╗  ██║██╔══██╗██╔═══██╗██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔════╝
//              ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒        ██║   ██████╔╝█████╗  ██╔██╗ ██║██║  ██║██║   ██║███████╗██║     ██║   ██║██████╔╝█████╗
//             ▒▒▒▒▒       ▒▒▒▒▒       ██║   ██╔══██╗██╔══╝  ██║╚██╗██║██║  ██║██║   ██║╚════██║██║     ██║   ██║██╔═══╝ ██╔══╝
//            ▒▒▒▒▒         ▒▒▒▒▒      ██║   ██║  ██║███████╗██║ ╚████║██████╔╝╚██████╔╝███████║╚██████╗╚██████╔╝██║     ███████╗
//             ▒▒             ▒
//@version=6

// @description Library having abstract types and methods for chart pattern implementations
library('abstractchartpatterns', overlay = true)

// import Trendoscope/ZigzagLite/2 as zg
import Trendoscope/LineWrapper/2 as wr
import Trendoscope/ohlc/3 as o

// @type Object containing properties for pattern drawing
// @field patternLineWidth Line width of the pattern trend lines
// @field showZigzag show zigzag associated with pattern
// @field zigzagLineWidth line width of the zigzag lines. Used only when showZigzag is set to true
// @field zigzagLineColor color of the zigzag lines. Used only when showZigzag is set to true
// @field showPatternLabel display pattern label containing the name
// @field patternLabelSize size of the pattern label. Used only when showPatternLabel is set to true
// @field showPivotLabels Display pivot labels of the patterns marking 1-6
// @field pivotLabelSize size of the pivot label. Used only when showPivotLabels is set to true
// @field pivotLabelColor color of the pivot label outline. chart.bg_color or chart.fg_color are the appropriate values.
// @field deleteOnPop delete the pattern when popping out from the array of Patterns.
export type DrawingProperties
	int patternLineWidth = 2
	bool showZigzag = true
	int zigzagLineWidth = 1
	color zigzagLineColor = color.blue
	bool showPatternLabel = true
	string patternLabelSize = size.normal
	bool showPivotLabels = true
	string pivotLabelSize = size.normal
	color pivotLabelColor = chart.bg_color
	bool deleteOnPop = false

// @type Object containing Individual Pattern data
// @field dir direction of the last pivot
// @field points array of Zigzag Pivot points
// @field trendLine1 First trend line joining pivots 1, 3, 5
// @field trendLine2 Second trend line joining pivots 2, 4 (, 6)
// @field properties DrawingProperties Object carrying common properties
// @field patternColor Individual pattern color. Lines and labels will be using this color.
// @field ratioDiff Difference between trendLine1 and trendLine2 ratios
// @field zigzagLine Internal zigzag line drawing Object
// @field pivotLabels array containning Pivot labels
// @field patternLabel pattern label Object
// @field patternType integer representing the pattern type
// @field patternName Type of pattern in string
export type Pattern
	int dir
	array<chart.point> points
	wr.Line trendLine1
	wr.Line trendLine2
	DrawingProperties properties
	color patternColor
	float ratioDiff
	polyline zigzagLine
	array<label> pivotLabels
	label patternLabel
	int patternType
	string patternName

// @type Object containing properties for pattern size filters
// @field filterByBar If set filter the patterns by the bar range
// @field minPatternBars Used only when filterByBar is set to true. Minimum bars range for pattern size
// @field maxPatternBars Used only when filterByBar is set to true. Maximum bars range for pattern size
// @field filterByPercent Filters patterns by percent of price if set
// @field minPatternPercent Used only when filterByPercent is set. Minimum pattern size in terms of percent of price
// @field maxPatternPercent Used only when filterByPercent is set. Maximum pattern size in terms of percent of price
export type SizeFilters
	bool filterByBar = false
	int minPatternBars = 0
	int maxPatternBars = 1000
	bool filterByPercent = false
	int minPatternPercent = 0
	int maxPatternPercent = 100

// @type Object containing properties for pattern scanning
// @field offset Zigzag pivot offset. Set it to 1 for non repainting scan.
// @field numberOfPivots Number of pivots to be used in pattern search. Can be either 5 or 6
// @field errorRatio Error Threshold to be considered for comparing the slope of lines
// @field flatRatio Retracement ratio threshold used to determine if the lines are flat
// @field checkBarRatio Also check bar ratio are within the limits while scanning the patterns
// @field barRatioLimit Bar ratio limit used for checking the bars. Used only when checkBarRatio is set to true
// @field avoidOverlap avoid overlapping patterns.
// @field ignoreIfEntryCrossed Ignore the trade if close price does not fall within the price entry price range
// @field allowedPatterns array of bool encoding the allowed pattern types.
// @field allowedLastPivotDirections array of int representing allowed last pivot direction for each pattern types
// @field themeColors color array of themes to be used.
export type ScanProperties
	int offset = 0
	int numberOfPivots = 5
	float errorRatio = 0.2
	float flatRatio = 0.2
	bool checkBarRatio = true
	float barRatioLimit = 0.382
	bool avoidOverlap = true
    bool ignoreIfEntryCrossed = false
	array<bool> allowedPatterns
	array<int> allowedLastPivotDirections
	array<color> themeColors
	SizeFilters filters


inRange(float value, float min, float max) =>
    value >= min and value <= max

// @function checks if the series of pivots are within the size filter
// @param filters SizeFilters object containing size criteria to be matched
// @param points list of pivot points
// @returns true if matches the size filter, false otherwise
export method checkSize(SizeFilters filters, array<chart.point> points) =>
    check = true
    if filters.filterByBar or filters.filterByPercent
        array<int> bars = array.new<int>()
        array<float> prices = array.new<float>()
        for p in points
            bars.push(p.index)
            prices.push(p.price)
        barDiff = bars.max() - bars.min()
        priceDiff = prices.max() - prices.min()
        pricePercentage = priceDiff / prices.max()
        check := check and (not filters.filterByBar or barDiff >= filters.minPatternBars and barDiff <= filters.maxPatternBars)
        check := check and (not filters.filterByPercent or pricePercentage >= filters.minPatternPercent and pricePercentage <= filters.maxPatternPercent)
        check
    check


// @function checks if three zigzag pivot points are having uniform bar ratios
// @param p1 First pivot point
// @param p2 Second pivot point
// @param p3 Third pivot point
// @param sProperties ScanProperties object
// @returns true if points are having uniform bar ratio
export checkBarRatio(chart.point p1, chart.point p2, chart.point p3, ScanProperties properties) =>
    r = math.abs(p3.index - p2.index) / math.abs(p2.index - p1.index)
    properties.checkBarRatio ? inRange(r, properties.barRatioLimit, 1 / properties.barRatioLimit) : true

// @function gets ratio difference between 3 pivot combinations
// @param pivot1 First pivot point
// @param pivot2 Second pivot point
// @param pivot3 Third pivot point
// @returns returns the ratio difference between pivot2/pivot1 ratio and pivot3/pivot2 ratio
export getRatioDiff(chart.point p1, chart.point p2, chart.point p3) =>
    firstRatio = (p2.price - p1.price) / (p2.index - p1.index)
    secondRatio = (p3.price - p2.price) / (p3.index - p2.index)
    math.abs(firstRatio - secondRatio)

method inspect(wr.Line ln, int stratingBar, int endingBar, int otherBar, float direction, array<o.OHLC> ohlcArray) =>
    valid = true
    score = 0.0
    total = 0.0
    for barIndex = stratingBar to endingBar by 1
        total := total + 1
        barOhlc = na(ohlcArray) ? o.OHLC.new(open[bar_index - barIndex], high[bar_index - barIndex], low[bar_index - barIndex], close[bar_index - barIndex]) : ohlcArray.size() <= barIndex ? o.OHLC.new(open[bar_index - barIndex], high[bar_index - barIndex], low[bar_index - barIndex], close[bar_index - barIndex]) : ohlcArray.get(barIndex)
        barPrice = direction > 0 ? barOhlc.h : barOhlc.l
        barOutPrice = direction > 0 ? barOhlc.l : barOhlc.h
        linePrice = ln.get_price(barIndex)
        if linePrice * direction < math.min(barOhlc.o * direction, barOhlc.c * direction)
            valid := false
            break
        if linePrice * direction >= barOutPrice * direction and linePrice * direction <= barPrice * direction
            score := score + 1
            score
        else if barIndex == otherBar
            valid := false
            break
    [valid and score / total < 0.2, score]

// @function Creates a trend line between 2 or 3 points and validates and selects best combination
// @param points Array of chart.point objects used for drawing trend line
// @param stratingBar starting bar of the trend line
// @param endingBar ending bar of the trend line
// @param direction direction of the last pivot. Tells whether the line is joining upper pivots or the lower pivots
// @param ohlcArray Array of OHLC values
// @returns boolean flag indicating if the trend line is valid and the trend line object as tuple
export method inspect(array<chart.point> points, int stratingBar, int endingBar, float direction, array<o.OHLC> ohlcArray) =>
    if points.size() == 3
        trendLine1 = wr.Line.new(points.first(), points.last())
        [valid1, score1] = trendLine1.inspect(stratingBar, endingBar, points.get(1).index, direction, ohlcArray)

        trendLine2 = wr.Line.new(points.first(), points.get(1))
        [valid2, score2] = trendLine2.inspect(stratingBar, endingBar, points.last().index, direction, ohlcArray)

        trendLine3 = wr.Line.new(points.get(1), points.last())
        [valid3, score3] = trendLine3.inspect(stratingBar, endingBar, points.first().index, direction, ohlcArray)

        returnItem = valid1 and score1 > math.max(score2, score3) ? 1 : valid2 and score2 > math.max(score1, score3) ? 2 : 3
        [returnItem == 1 ? valid1 : returnItem == 2 ? valid2 : valid3, returnItem == 1 ? trendLine1 : returnItem == 2 ? trendLine2 : trendLine3]
    else
        trendLine = wr.Line.new(points.first(), points.last())
        [valid, score] = trendLine.inspect(stratingBar, endingBar, points.first().index, direction, ohlcArray)
        [valid, trendLine]

// @function draws pattern on the chart
// @param this Pattern object that needs to be drawn
// @returns Current Pattern object
export method draw(Pattern this) =>
    this.trendLine1.xloc := xloc.bar_time
    this.trendLine2.xloc := xloc.bar_time
    this.trendLine1.draw()
    this.trendLine2.draw()

    if this.properties.showZigzag
        this.zigzagLine := polyline.new(this.points, line_color = this.properties.zigzagLineColor, line_width = this.properties.zigzagLineWidth, line_style = line.style_dotted, xloc = xloc.bar_time)
        this.zigzagLine
    if this.properties.showPatternLabel
        patternStyle = this.dir > 0 ? label.style_label_lower_left : label.style_label_upper_left
        this.patternLabel := label.new(this.points.last(), this.patternName, color = this.patternColor, textcolor = chart.bg_color, style = patternStyle, size = this.properties.patternLabelSize, xloc = xloc.bar_time)
        this.patternLabel
    if this.properties.showPivotLabels
        if na(this.pivotLabels)
            this.pivotLabels := array.new<label>()
            this.pivotLabels
        for [i, point] in this.points
            labelStyle = label.style_text_outline
            labelYloc = yloc.price
            this.pivotLabels.push(label.new(point, str.tostring(i + 1), yloc = labelYloc, style = labelStyle, color = this.properties.pivotLabelColor, textcolor = this.patternColor, size = this.properties.pivotLabelSize, xloc = xloc.bar_time))
    this

// @function erase the given pattern on the chart
// @param this Pattern object that needs to be erased
// @returns Current Pattern object
export method erase(Pattern this) =>
    this.trendLine1.delete()
    this.trendLine2.delete()
    this.zigzagLine.delete()
    this.patternLabel.delete()
    if not na(this.pivotLabels)
        while this.pivotLabels.size() > 0
            this.pivotLabels.pop().delete()
    this


// @function push Pattern object to the array by keeping maxItems limit
// @param this array of Pattern objects
// @param p Pattern object to be added to array
// @oaram maxItems Max number of items the array can hold
// @returns Current Pattern array
export method push(array<Pattern> this, Pattern p, int maxItems) =>
    this.push(p)
    while this.size() > maxItems
        removedPattern = this.shift()
        if removedPattern.properties.deleteOnPop
            removedPattern.erase()

// @function Perform deep copy of a chart point array
// @param this array of chart.point objects
// @returns deep copy array
export method deepcopy(array<chart.point> this) =>
    copy = array.new<chart.point>()
    for point in this
        copy.push(point.copy())
    copy
