// This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © Trendoscope Pty Ltd, Trendoscope®
//                                       ░▒
//                                  ▒▒▒   ▒▒
//                              ▒▒▒▒▒     ▒▒
//                      ▒▒▒▒▒▒▒░     ▒     ▒▒
//                  ▒▒▒▒▒▒           ▒     ▒▒
//             ▓▒▒▒       ▒        ▒▒▒▒▒▒▒▒▒▒▒
//   ▒▒▒▒▒▒▒▒▒▒▒ ▒        ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
//   ▒  ▒       ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░
//   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒
//   ▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒
//    ▒▒▒▒▒         ▒▒▒▒▒▒▒
//                 ▒▒▒▒▒▒▒▒▒
//                ▒▒▒▒▒ ▒▒▒▒▒
//               ░▒▒▒▒   ▒▒▒▒▓      ████████╗██████╗ ███████╗███╗   ██╗██████╗  ██████╗ ███████╗ ██████╗ ██████╗ ██████╗ ███████╗
//              ▓▒▒▒▒     ▒▒▒▒      ╚══██╔══╝██╔══██╗██╔════╝████╗  ██║██╔══██╗██╔═══██╗██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔════╝
//              ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒        ██║   ██████╔╝█████╗  ██╔██╗ ██║██║  ██║██║   ██║███████╗██║     ██║   ██║██████╔╝█████╗
//             ▒▒▒▒▒       ▒▒▒▒▒       ██║   ██╔══██╗██╔══╝  ██║╚██╗██║██║  ██║██║   ██║╚════██║██║     ██║   ██║██╔═══╝ ██╔══╝
//            ▒▒▒▒▒         ▒▒▒▒▒      ██║   ██║  ██║███████╗██║ ╚████║██████╔╝╚██████╔╝███████║╚██████╗╚██████╔╝██║     ███████╗
//             ▒▒             ▒
//@version=6

// @description Library having complete chart pattern implementation
library('basechartpatterns', overlay = true)

import Trendoscope/ZigzagLite/3 as zg
import Trendoscope/LineWrapper/2 as wr
import Trendoscope/ohlc/3 as o
import Trendoscope/abstractchartpatterns/9 as p

// @function Returns pattern name by id
// @param id pattern id
// @returns Pattern name
export getPatternNameById(int id) =>
    switch id
        1 => 'Ascending Channel'
        2 => 'Descending Channel'
        3 => 'Ranging Channel'
        4 => 'Rising Wedge (Expanding)'
        5 => 'Falling Wedge (Expanding)'
        6 => 'Diverging Triangle'
        7 => 'Ascending Triangle (Expanding)'
        8 => 'Descending Triangle (Expanding)'
        9 => 'Rising Wedge (Contracting)'
        10 => 'Falling Wedge (Contracting)'
        11 => 'Converging Triangle'
        12 => 'Descending Triangle (Contracting)'
        13 => 'Ascending Triangle (Contracting)'
        => 'Error'

method resolvePatternName(p.Pattern this, p.ScanProperties properties) =>
    t1p1 = this.trendLine1.p1.price
    t1p2 = this.trendLine1.p2.price
    t2p1 = this.trendLine2.p1.price
    t2p2 = this.trendLine2.p2.price

    upperAngle = t1p1 > t2p1 ? (t1p2 - math.min(t2p1, t2p2)) / (t1p1 - math.min(t2p1, t2p2)) : (t2p2 - math.min(t1p1, t1p2)) / (t2p1 - math.min(t1p1, t1p2))
    lowerAngle = t1p1 > t2p1 ? (t2p2 - math.max(t1p1, t1p2)) / (t2p1 - math.max(t1p1, t1p2)) : (t1p2 - math.max(t2p1, t2p2)) / (t1p1 - math.max(t2p1, t2p2))

    upperLineDir = upperAngle > 1 + properties.flatRatio ? 1 : upperAngle < 1 - properties.flatRatio ? -1 : 0
    lowerLineDir = lowerAngle > 1 + properties.flatRatio ? -1 : lowerAngle < 1 - properties.flatRatio ? 1 : 0

    startDiff = math.abs(this.trendLine1.p1.price - this.trendLine2.p1.price)
    endDiff = math.abs(this.trendLine1.p2.price - this.trendLine2.p2.price)

    minDiff = math.min(startDiff, endDiff)
    barDiff = this.trendLine1.p2.index - this.trendLine2.p1.index
    priceDiff = math.abs(startDiff - endDiff) / barDiff

    probableConvergingBars = minDiff / priceDiff

    isExpanding = math.abs(t1p2 - t2p2) > math.abs(t1p1 - t2p1)
    isContracting = math.abs(t1p2 - t2p2) < math.abs(t1p1 - t2p1)

    isChannel = probableConvergingBars > 2 * barDiff or not isExpanding and not isContracting or upperLineDir == 0 and lowerLineDir == 0
    invalid = math.sign(t1p1 - t2p1) != math.sign(t1p2 - t2p2)
    this.patternType := invalid ? 0 : isChannel ? upperLineDir > 0 and lowerLineDir > 0 ? 1 : upperLineDir < 0 and lowerLineDir < 0 ? 2 : upperLineDir == 0 and lowerLineDir == 0 ? 3 : 3 : isExpanding ? upperLineDir > 0 and lowerLineDir > 0 ? 4 : upperLineDir < 0 and lowerLineDir < 0 ? 5 : upperLineDir > 0 and lowerLineDir < 0 ? 6 : upperLineDir > 0 and lowerLineDir == 0 ? 7 : upperLineDir == 0 and lowerLineDir < 0 ? 8 : -2 : isContracting ? upperLineDir > 0 and lowerLineDir > 0 ? 9 : upperLineDir < 0 and lowerLineDir < 0 ? 10 : upperLineDir < 0 and lowerLineDir > 0 ? 11 : lowerLineDir == 0 ? upperLineDir < 0 ? 12 : 1 : upperLineDir == 0 ? lowerLineDir > 0 ? 13 : 2 : -3 : -4
    if this.patternType < 0
        log.info('Wrong Type detected {0}, Dirs : {1}, {2}, Invalid : {7}, Prices: {3}, {4}, {5}. {6}', this.patternType, upperLineDir, lowerLineDir, t1p1, t1p2, t2p1, t2p2, invalid)
        this.patternType := 0
        this.patternType
    this

method resolve(p.Pattern this, p.ScanProperties properties) =>
    firstIndex = this.points.first().index
    lastIndex = this.points.last().index
    firstTime = this.points.first().time
    lastTime = this.points.last().time
    this.trendLine1.p1 := chart.point.new(firstTime, firstIndex, this.trendLine1.get_price(firstIndex))
    this.trendLine1.p2 := chart.point.new(lastTime, lastIndex, this.trendLine1.get_price(lastIndex))

    this.trendLine1.color := this.patternColor

    this.trendLine2.p1 := chart.point.new(firstTime, firstIndex, this.trendLine2.get_price(firstIndex))
    this.trendLine2.p2 := chart.point.new(lastTime, lastIndex, this.trendLine2.get_price(lastIndex))
    this.trendLine2.color := this.patternColor

    for [i, point] in this.points
        currentTrendLine = i % 2 == 1 ? this.trendLine2 : this.trendLine1
        point.price := currentTrendLine.get_price(point.index)
        point.price

    this.resolvePatternName(properties)
    this

// @function Find patterns based on array of points
// @param points array of chart.point objects
// @param properties ScanProperties object
// @param dProperties DrawingProperties object
// @param array of OHLC values.
// @returns Flag indicating if the pattern is valid, Current Pattern object
export method find(array<chart.point> points, p.ScanProperties properties, p.DrawingProperties dProperties, array<o.OHLC> ohlcArray = na) =>
    validPattern = properties.numberOfPivots == 6 ? p.checkBarRatio(points.get(1), points.get(3), points.get(5), properties) and p.checkBarRatio(points.get(0), points.get(2), points.get(4), properties) : p.checkBarRatio(points.get(0), points.get(2), points.get(4), properties)
    p.Pattern currentPattern = na
    if validPattern
        trendPointArray1 = array.from(points.get(0), points.get(2), points.get(4))
        trendPointArray2 = properties.numberOfPivots == 6 ? array.from(points.get(1), points.get(3), points.get(5)) : array.from(points.get(1), points.get(3))

        firstIndex = points.first().index
        lastIndex = points.last().index
        firstDirection = points.get(0).price > points.get(1).price ? 1 : -1
        [valid1, trendLine1] = trendPointArray1.inspect(firstIndex, lastIndex, math.sign(firstDirection), ohlcArray)
        [valid2, trendLine2] = trendPointArray2.inspect(firstIndex, lastIndex, math.sign(-firstDirection), ohlcArray)
        if valid1 and valid2
            if na(properties.themeColors)
                properties.themeColors := array.from(color.blue)
                properties.themeColors

            if properties.themeColors.size() == 0
                properties.themeColors.push(color.blue)

            patternColor = properties.themeColors.shift()
            properties.themeColors.push(patternColor)
            trendLine1.width := dProperties.patternLineWidth
            trendLine2.width := dProperties.patternLineWidth
            ratioDiff = properties.numberOfPivots == 6 ? p.getRatioDiff(points.get(1), points.get(3), points.get(5)) : p.getRatioDiff(points.get(0), points.get(2), points.get(4))
            lastDir = int(math.sign(points.last().price - points.get(points.size() - 2).price))
            currentPattern := p.Pattern.new(lastDir, points, trendLine1, trendLine2, dProperties, patternColor, ratioDiff).resolve(properties)

            allowedLastPivotDirection = na(properties.allowedLastPivotDirections) or properties.allowedLastPivotDirections.size() <= currentPattern.patternType ? 0 : properties.allowedLastPivotDirections.get(currentPattern.patternType)

            allowedPattern = (na(properties.allowedPatterns) ? true : properties.allowedPatterns.size() <= currentPattern.patternType ? false : currentPattern.patternType >= 0 ? properties.allowedPatterns.get(currentPattern.patternType) : false) and (allowedLastPivotDirection == 0 or allowedLastPivotDirection == lastDir)
            if allowedPattern
                currentPattern.patternName := getPatternNameById(currentPattern.patternType)
                currentPattern.patternName
            else
                validPattern := false
                validPattern
        else
            validPattern := false
            validPattern
    [validPattern, currentPattern]

// @function Find patterns based on the currect zigzag object but will not store them in the pattern array.
// @param this Zigzag object containing pivots
// @param properties ScanProperties object
// @param dProperties DrawingProperties object
// @param patterns Array of Pattern objects
// @param array of OHLC values.
// @returns Flag indicating if the pattern is valid, Current Pattern object
export method find(zg.Zigzag this, p.ScanProperties properties, p.DrawingProperties dProperties, array<p.Pattern> patterns = na, array<o.OHLC> ohlcArray = na) =>
    p6 = this.zigzagPivots.get(0 + properties.offset).point.copy()
    p5 = this.zigzagPivots.get(1 + properties.offset).point.copy()
    p4 = this.zigzagPivots.get(2 + properties.offset).point.copy()
    p3 = this.zigzagPivots.get(3 + properties.offset).point.copy()
    p2 = this.zigzagPivots.get(4 + properties.offset).point.copy()
    p1 = properties.numberOfPivots == 6 ? this.zigzagPivots.get(5 + properties.offset).point.copy() : na

    p.Pattern currentPattern = na
    array<chart.point> points = properties.numberOfPivots == 6 ? array.from(p1, p2, p3, p4, p5, p6) : array.from(p2, p3, p4, p5, p6)
    ignorePattern = false
    existingPattern = false

    for [index, pattern] in patterns
        startBar = pattern.points.first().index
        endBar = pattern.points.last().index
        currentStartBar = points.first().index
        currentLastBar = points.last().index

        if currentStartBar > startBar and currentStartBar < endBar and properties.avoidOverlap
            ignorePattern := true
            break
        match = true
        for i = 0 to properties.numberOfPivots - 2 by 1
            cp = points.get(i)
            ep = pattern.points.get(i)
            if cp.index != ep.index
                match := false
                break
        if match
            existingPattern := true
            existingPattern

    validPattern = not(ignorePattern or existingPattern)
    if validPattern
        [valid, pattern] = points.find(properties, dProperties, ohlcArray)
        validPattern := valid
        currentPattern := pattern
        currentPattern

    [validPattern, currentPattern]
