export type ElliottTheoryCodeStatus = "aligned" | "partial" | "missing";

export type ElliottTheoryCodeReference = {
  file: string;
  note?: string;
};

export type ElliottTheoryCodeFinding = {
  id: string;
  status: ElliottTheoryCodeStatus;
  title: string;
  summary: string;
  theory: string;
  code: string;
  impact: string;
  references?: readonly ElliottTheoryCodeReference[];
};

const ALIGNED: readonly ElliottTheoryCodeFinding[] = [
  {
    id: "impulse_rule_w2_not_beyond_w1_start",
    status: "aligned",
    title: "Impulse: W2 cannot retrace beyond W1 start",
    summary: "Hard invalidation is implemented.",
    theory: "Wave 2 cannot retrace beyond the start of Wave 1 (100% retracement invalidates the count).",
    code: "Check `w2_not_beyond_w1_start` is applied for both bull and bear impulse candidates.",
    impact: "Prevents invalid impulses from becoming candidate/confirmed.",
    references: [{ file: "web/src/lib/elliottEngineV2/impulse.ts", note: "`w2_not_beyond_w1_start`" }],
  },
  {
    id: "impulse_rule_w3_not_shortest",
    status: "aligned",
    title: "Impulse: W3 cannot be the shortest among 1/3/5",
    summary: "Hard invalidation is implemented.",
    theory: "Wave 3 cannot be the shortest among waves 1, 3 and 5.",
    code: "Check `w3_not_shortest_135` is applied for both bull and bear impulse candidates.",
    impact: "Eliminates a broad class of miscounts.",
    references: [{ file: "web/src/lib/elliottEngineV2/impulse.ts", note: "`w3_not_shortest_135`" }],
  },
  {
    id: "impulse_rule_w4_no_overlap_standard",
    status: "aligned",
    title: "Impulse: W4 must not overlap W1 (standard impulse)",
    summary: "Hard invalidation is implemented for the standard impulse variant.",
    theory: "In a standard impulse, wave 4 cannot enter wave 1 price territory.",
    code: "Check `w4_no_overlap_w1` is enforced in `variant: standard` impulse checks.",
    impact: "Maintains the classical separation between standard impulse and diagonal variants.",
    references: [{ file: "web/src/lib/elliottEngineV2/impulse.ts", note: "`w4_no_overlap_w1` (standard)" }],
  },
  {
    id: "impulse_rule_w3_not_below_w1_end_bull",
    status: "aligned",
    title: "Impulse (bull): W3 cannot be below W1 end",
    summary: "Hard invalidation is implemented.",
    theory: "In bull impulses, wave 3 must not fall below wave 1 end price.",
    code: "Check `w3_not_below_w1_end` is included in bull impulse checks.",
    impact: "Reduces false bull impulses in choppy ranges.",
    references: [{ file: "web/src/lib/elliottEngineV2/impulse.ts", note: "`w3_not_below_w1_end`" }],
  },
  {
    id: "impulse_rule_w3_not_above_w1_end_bear",
    status: "aligned",
    title: "Impulse (bear): W3 cannot be above W1 end",
    summary: "Hard invalidation is implemented.",
    theory: "In bear impulses, wave 3 must not rise above wave 1 end price (mirror rule).",
    code: "Check `w3_not_above_w1_end` is included in bear impulse checks.",
    impact: "Improves bear symmetry correctness.",
    references: [{ file: "web/src/lib/elliottEngineV2/impulse.ts", note: "`w3_not_above_w1_end`" }],
  },
  {
    id: "zigzag_rule_b_vs_a_band",
    status: "aligned",
    title: "Zigzag: B/A ratio band (0.382–0.618)",
    summary: "Zigzag B retracement band is implemented.",
    theory: "Zigzag B should typically retrace between ~38.2% and 61.8% of A (and not exceed the high limit).",
    code: "`zz_r5` enforces B/A within a bounded range.",
    impact: "Separates zigzags from flats and reduces mislabels.",
    references: [{ file: "web/src/lib/elliottEngineV2/tezWaveChecks.ts", note: "`TEZ_ZIGZAG_B_VS_A_*` / `zz_r5`" }],
  },
  {
    id: "zigzag_rule_c_ge_b",
    status: "aligned",
    title: "Zigzag: |C| cannot be shorter than |B|",
    summary: "Implemented as a directional-length check.",
    theory: "For zigzags, C should not be shorter than B (common guideline; used as a filter).",
    code: "`zz_r1` checks `|C| >= |B|` using A→B and B→C legs.",
    impact: "Reduces weak zigzag candidates that do not progress.",
    references: [{ file: "web/src/lib/elliottEngineV2/tezWaveChecks.ts", note: "`zz_r1`" }],
  },
  {
    id: "zigzag_rule_c_beyond_a_end",
    status: "aligned",
    title: "Zigzag: C must go beyond A end",
    summary: "Implemented as a directional check.",
    theory: "Zigzag wave C typically exceeds wave A’s endpoint.",
    code: "`zz_r6` checks that C_end exceeds A_end in the correct direction.",
    impact: "Prevents classifying shallow 3-leg moves as a zigzag.",
    references: [{ file: "web/src/lib/elliottEngineV2/tezWaveChecks.ts", note: "`zz_r6`" }],
  },
  {
    id: "zigzag_rule_b_not_beyond_a_start",
    status: "aligned",
    title: "Zigzag: B must not go beyond A start",
    summary: "Implemented as a direction-aware guard.",
    theory: "B should not exceed A origin in a standard zigzag.",
    code: "`zz_b_not_beyond_a_start` enforces B relative to A start by trend direction.",
    impact: "Avoids labeling B-overruns as simple zigzags.",
    references: [{ file: "web/src/lib/elliottEngineV2/tezWaveChecks.ts", note: "`zz_b_not_beyond_a_start`" }],
  },
  {
    id: "flat_rule_c_vs_a_min",
    status: "aligned",
    title: "Flat: C/A minimum (0.382)",
    summary: "Implemented as a numeric check.",
    theory: "Flat C should meet a minimum magnitude relative to A (used as a filter).",
    code: "`flat_g7` checks `C/A >= TEZ_FLAT_C_VS_A_MIN`.",
    impact: "Removes very weak C legs from flat candidates.",
    references: [{ file: "web/src/lib/elliottEngineV2/tezWaveChecks.ts", note: "`flat_g7` / `TEZ_FLAT_C_VS_A_MIN`" }],
  },
  {
    id: "triangle_rule_channel",
    status: "aligned",
    title: "Triangle: channel containment (tri_r2)",
    summary: "Triangle channel rule is implemented.",
    theory: "Triangle pivots should remain within the A–C / B–D channel; E deviation bounded.",
    code: "Triangle checks include `tri_r2_channel` and an E deviation limit.",
    impact: "Reduces false triangles that do not fit channel geometry.",
    references: [{ file: "web/src/lib/elliottEngineV2/corrective.ts", note: "`tri_r2_*` checks" }],
  },
  {
    id: "triangle_rule_apex_after_e",
    status: "aligned",
    title: "Triangle: apex timing after E (tri_r3)",
    summary: "Apex / convergence timing check is implemented.",
    theory: "Triangle should complete before the channel lines intersect (apex not before E end).",
    code: "Triangle checks include an apex-after-E constraint (`tri_r3_*`).",
    impact: "Prevents triangles that are geometrically inconsistent.",
    references: [{ file: "web/src/lib/elliottEngineV2/corrective.ts", note: "`tri_r3_*` checks" }],
  },
  {
    id: "triangle_rule_not_parallel",
    status: "aligned",
    title: "Triangle: lines must not be parallel (tri_r4)",
    summary: "Parallel rejection is implemented.",
    theory: "Triangle boundary lines should converge or diverge; they are not parallel.",
    code: "Triangle checks include `tri_r4_not_parallel`.",
    impact: "Avoids classifying channels as triangles.",
    references: [{ file: "web/src/lib/elliottEngineV2/corrective.ts", note: "`tri_r4_not_parallel`" }],
  },
  {
    id: "wxyxz_fib_bands",
    status: "aligned",
    title: "WXYXZ: Fibonacci bands and connector constraints",
    summary: "WXYXZ ratio-band and connector checks exist.",
    theory: "WXYXZ combinations use ratio bands (W≈Y, Z extension) and connector retrace constraints.",
    code: "Corrective checks include ratio bands and X connector bounds (wxyxz_* checks).",
    impact: "Improves discrimination between combinations and random chop.",
    references: [{ file: "web/src/lib/elliottEngineV2/corrective.ts", note: "wxyxz_* checks" }],
  },
  {
    id: "bear_symmetry_impulse_checks",
    status: "aligned",
    title: "Bear symmetry: impulse checks mirrored",
    summary: "Bear impulse path mirrors bull impulse checks.",
    theory: "Impulse rules apply identically in reverse for bear markets.",
    code: "Separate `checksBear`/`checksBearDiagonal` mirror `checksBull` logic with reversed inequalities.",
    impact: "Avoids bull-biased detection behavior.",
    references: [{ file: "web/src/lib/elliottEngineV2/impulse.ts", note: "checksBear* implementations" }],
  },
  {
    id: "nested_search_present",
    status: "aligned",
    title: "Nested subwave search exists (impulse legs)",
    summary: "The engine can search for nested impulse structures within legs.",
    theory: "Lower-degree subdivision should exist (fractal property).",
    code: "Nested detection helpers exist for wave legs using micro zigzag and best-window selection.",
    impact: "Provides evidence and overlays for internal structure (even if not a hard gate).",
    references: [{ file: "web/src/lib/elliottEngineV2/impulse.ts", note: "`detectNestedImpulseInLeg`" }],
  },
  {
    id: "engine_state_model_present",
    status: "aligned",
    title: "State model: invalid / candidate / confirmed",
    summary: "Engine emits the 3-state decision model.",
    theory: "Counts should be classified by confidence (invalid/candidate/confirmed).",
    code: "Engine state includes `decision` and merges across TF hierarchy.",
    impact: "Allows UI to display uncertainty rather than binary truth claims.",
    references: [{ file: "web/src/lib/elliottEngineV2/engine.ts", note: "decision output" }],
  },
  {
    id: "projection_scope_documented",
    status: "aligned",
    title: "Forward projection scope is documented in standards",
    summary: "Projection behavior is explicitly described and scoped.",
    theory: "Projection is a heuristic layer; must not be conflated with strict validation.",
    code: "Standards doc maps projection behavior to implementation.",
    impact: "Reduces mismatched expectations between UI and engine.",
    references: [{ file: "docs/ELLIOTT_V2_STANDARDS.md", note: "§8.1 projection behavior" }],
  },
  {
    id: "diagonal_variant_exists",
    status: "aligned",
    title: "Diagonal motive variant exists (overlap allowed)",
    summary: "Engine supports a diagonal impulse variant with extra checks.",
    theory: "Diagonals are a separate motive variant where W4 overlap can occur.",
    code: "Impulse detector evaluates `variant: diagonal` with dedicated checks (`ed_r4`, `w5_not_longest`, `ld_r3` as a soft score — not a hard invalidation).",
    impact: "Enables wedge-like motive candidates instead of forcing standard impulse.",
    references: [{ file: "web/src/lib/elliottEngineV2/impulse.ts", note: "`checks*Diagonal`" }],
  },
  {
    id: "triangle_context_checks_exist",
    status: "aligned",
    title: "Triangle: context checks exist (wave4/B/post)",
    summary: "Triangle detection is constrained by context checks.",
    theory: "Triangles appear in specific contexts (often wave 4 or B; not arbitrary).",
    code: "Corrective checks include context labels (e.g., wave4-or-B gating).",
    impact: "Reduces standalone triangle false positives.",
    references: [{ file: "web/src/lib/elliottEngineV2/corrective.ts", note: "triangle context checks" }],
  },
  {
    id: "combination_scoring_exists",
    status: "aligned",
    title: "Combination: WXY and WXYXZ scoring exists",
    summary: "Combination candidates have explicit checks for alternation/progress/ratios.",
    theory: "Combinations require connectors and progression, not just three arbitrary legs.",
    code: "Corrective checks include `comb_*` and `wxyxz_*` checks.",
    impact: "Allows more robust classification than pure ratio matching.",
    references: [{ file: "web/src/lib/elliottEngineV2/corrective.ts", note: "comb_* / wxyxz_* checks" }],
  },
  {
    id: "flat_vs_zigzag_separation_exists",
    status: "aligned",
    title: "Flat vs zigzag: classifier exists (label separation)",
    summary: "Engine/UI has a separation heuristic between flat and zigzag candidates.",
    theory: "Flat and zigzag should be separated by structure/ratios (especially B/A).",
    code: "There is a classifier used to label candidates separately in the corrective pipeline/UI.",
    impact: "Improves interpretability even when candidate nets are wide.",
    references: [{ file: "web/src/lib/elliottEngineV2/corrective.ts", note: "flat vs zigzag classifier" }],
  },
  {
    id: "abc_retr_b_gap_prefilter",
    status: "aligned",
    title: "ABC: ambiguous B/A gap band is rejected early",
    summary: "B/A between the zigzag ceiling and the flat label floor is filtered out before labeling.",
    theory: "The band between a typical zigzag B/A cap and a regular flat B/A floor is structurally ambiguous.",
    code: "`abcRetrBPassesPrefilter` returns false when `retrB` is between `TEZ_ZIGZAG_B_VS_A_MAX` and `FLAT_LABEL_MIN_RETR_B` (see `corrective.ts`).",
    impact: "Reduces false ABC candidates that sit between zigzag and flat interpretations.",
    references: [{ file: "web/src/lib/elliottEngineV2/corrective.ts", note: "`abcRetrBPassesPrefilter`" }],
  },
  {
    id: "triangle_leg_chain_monotonic",
    status: "aligned",
    title: "Triangle: contracting / expanding leg-length chain",
    summary: "Contracting triangles require strictly shrinking A–E spans; expanding require strictly growing spans.",
    theory: "Contracting: each successive leg is smaller than the prior (B<A, C<B, D<C, E<D). Expanding: the reverse.",
    code: "`findTriangleBetween` rejects candidates when `kindContract` / `kindExpand` applies but the span chain fails (`triangle_chain_contract` / `triangle_chain_expand`).",
    impact: "Reduces false triangles that only tighten late.",
    references: [{ file: "web/src/lib/elliottEngineV2/corrective.ts", note: "`findTriangleBetween`" }],
  },
  {
    id: "triangle_leg_nested_corrective_proof",
    status: "aligned",
    title: "Triangle: A–E each has nested corrective-3 check ids",
    summary: "Per-leg nested corrective search appends `tri_*_corrective3` checks; `confirmed` requires them.",
    theory: "Triangle is 3-3-3-3-3: each leg should subdivide as a corrective three at the next lower degree.",
    code: "`addTriangleLegProof` in `engine.ts` runs `detectNestedCorrectiveInLeg` on each `path[i]→path[i+1]`; `correctiveIsConfirmed` for triangle requires all five.",
    impact: "Triangles need internal evidence, not only channel geometry.",
    references: [{ file: "web/src/lib/elliottEngineV2/engine.ts", note: "`addTriangleLegProof`" }],
  },
  {
    id: "nested_wave3_impulse_no_diagonal",
    status: "aligned",
    title: "Nested Wave 3 leg: diagonal disallowed",
    summary: "Wave 3 internal nested impulse search never allows the diagonal variant.",
    theory: "Wave 3 must be a true impulse, not a diagonal (strict reading).",
    code: "`runForTf` calls `detectNestedImpulseInLeg` for W2→W3 with `{ ...opts, allowDiagonal: false }`.",
    impact: "Prevents diagonal miscounts inside the strongest motive leg.",
    references: [{ file: "web/src/lib/elliottEngineV2/engine.ts", note: "wave3 nested impulse opts" }],
  },
  {
    id: "combination_y_zigzag_cap",
    status: "aligned",
    title: "Combination: at most one zigzag in Y (comb_r8)",
    summary: "W–X–Y candidates are rejected when more than one disjoint zigzag ABC is found in the Y segment.",
    theory: "Double/triple combinations typically allow at most one zigzag among the corrective legs.",
    code: "`countDisjointZigzagsInY` + `comb_r8_y_zigzag_cap`; `findCombinationBetween` returns null when the cap fails.",
    impact: "Fewer over-fitted W–X–Y paths in noisy pivot sequences.",
    references: [{ file: "web/src/lib/elliottEngineV2/corrective.ts", note: "`findCombinationBetween`" }],
  },
  {
    id: "combination_y_triangle_last",
    status: "aligned",
    title: "Combination: triangle-like geometry only at end of Y (comb_r9)",
    summary:
      "If the Y segment is long enough, a triangle match on its first six pivots without a match on its last six rejects the W–X–Y candidate.",
    theory: "In complex combinations, a triangle is often expected as the final corrective segment.",
    code: "`combinationTriangleLastInYSegmentOk` + `comb_r9_y_triangle_last`; gated with `comb_r1–r4` and `comb_r8`.",
    impact: "Reduces early-triangle / late-non-triangle pathologies inside Y.",
    references: [{ file: "web/src/lib/elliottEngineV2/corrective.ts", note: "`findCombinationBetween`" }],
  },
  {
    id: "diagonal_interpret_ending_documented",
    status: "aligned",
    title: "Diagonal: ending interpretation is explicit in checks",
    summary: "Diagonal impulse checks include an informational rule id that documents default interpretation.",
    theory: "Leading and ending diagonals differ; impulse checks document the engine’s default reading for a single 5-leg window.",
    code: "`diagonal_interpret_ending` is emitted on diagonal variants (bull/bear) in `checksBullDiagonal` / `checksBearDiagonal`.",
    impact: "UI notes default single-window interpretation; ld_r3 is scoped to leading role in `addDiagonalSubwaveProof`.",
    references: [{ file: "web/src/lib/elliottEngineV2/impulse.ts", note: "`diagonal_interpret_ending`" }],
  },
  {
    id: "diagonal_role_chart_heuristic",
    status: "aligned",
    title: "Diagonal: leading vs ending role hint from chart window",
    summary:
      "When `variant: diagonal`, the engine sets `diagonalRole` from the chart window unless MTF overlap overrides (`applyMtfDiagonalRefinement`).",
    theory:
      "Leading vs ending diagonals follow different internal compositions; chart position is a practical prior when parent wave degree is unknown.",
    code: "`inferDiagonalRoleFromChart` + `diagonal_role_hint`; `buildDiagonalSubwaveProof` branches on `leading` vs `ending`/`unknown`; optional `diagonalRoleSource`.",
    impact: "Ending uses 3-3-3-3-3-style nested ABC checks; leading uses 5-3-5-3-5-style nested motive/corrective checks.",
    references: [{ file: "web/src/lib/elliottEngineV2/engine.ts", note: "`inferDiagonalRoleFromChart`" }],
  },
  {
    id: "failed_fifth_truncation_structure",
    status: "aligned",
    title: "Truncation (failed fifth): W5 nested proof must be standard impulse",
    summary:
      "When `extension_w5_vs_w3` fails, `confirmed` requires `wave5NestedImpulse` with `variant: standard` (diagonal inner five does not qualify). W5 nested search uses `allowDiagonal: false`.",
    theory:
      "A truncated fifth must still show a complete five-wave motive at the next lower degree; that inner structure is a standard impulse, not a diagonal.",
    code: "`decideTimeframeState` + `detectNestedImpulseInLeg` for wave 5 in `engine.ts`.",
    impact: "Truncation confidence matches strict impulse subdivision expectations.",
    references: [
      { file: "web/src/lib/elliottEngineV2/engine.ts", note: "`decideTimeframeState` / wave5 nested opts" },
      { file: "web/src/lib/elliottEngineV2/impulse.ts", note: "`extension_w5_vs_w3`" },
    ],
  },
  {
    id: "flat_b_vs_a_min_is_wide",
    status: "aligned",
    title: "Flat: B/A label floor and expanded tag in checks",
    summary:
      "`flat_r4` keeps the wide Tez band for geometry; flat-labeled ABC uses `classifyFlatVsZigzag` ≥0.9 plus explicit `flat_ba_label_floor` and `flat_ba_variant_expanded` checks.",
    theory: "Regular vs expanded flats are distinguished by B/A (≥0.9 label floor; ≥1.0 expanded) alongside the ambiguous-band prefilter.",
    code: "`TEZ_FLAT_LABEL_MIN_RETR_B`, `buildTez254AbcChecks`, `abcRetrBPassesPrefilter` in `tezWaveChecks.ts` / `corrective.ts`.",
    impact: "Check ids expose label/variant; zigzag–flat ambiguity band remains filtered upstream.",
    references: [
      { file: "web/src/lib/elliottEngineV2/tezWaveChecks.ts", note: "`flat_ba_label_floor` / `flat_ba_variant_expanded`" },
      { file: "web/src/lib/elliottEngineV2/corrective.ts", note: "`classifyFlatVsZigzag`" },
    ],
  },
  {
    id: "nested_subwave_quality_not_in_decision",
    status: "aligned",
    title: "`confirmed` uses pattern proofs; optional wave1–5 overlays stay informational",
    summary:
      "Decision uses `correctiveIsConfirmed`, diagonal leg proofs, and truncation rules; `wave1NestedImpulse`…`wave5NestedImpulse` remain UI overlays without duplicating those gates.",
    theory: "Avoid double-counting the same structural evidence while still exposing optional nested views.",
    code: "`runForTf` vs `decideTimeframeState` in `engine.ts`.",
    impact: "Clear separation between hard gates and exploratory overlays.",
    references: [{ file: "web/src/lib/elliottEngineV2/engine.ts", note: "`decideTimeframeState`" }],
  },
  {
    id: "ld_r3_applied_to_all_diagonals",
    status: "aligned",
    title: "Diagonal: ld_r3 applied only when chart role is leading",
    summary:
      "`mapLdR3ByDiagonalRole` neutralizes `ld_r3_w5_ge_1382_w4` for ending/unknown so scores are not penalized by a leading-only rule.",
    theory: "ld_r3 (|5| ≥ 1.382×|4|) is a leading-diagonal guideline, not an ending-diagonal requirement.",
    code: "`mapLdR3ByDiagonalRole` in `engine.ts` inside `addDiagonalSubwaveProof`.",
    impact: "Ending diagonals are not down-scored by ld_r3; leading diagonals still show the ratio.",
    references: [
      { file: "web/src/lib/elliottEngineV2/engine.ts", note: "`mapLdR3ByDiagonalRole`" },
      { file: "web/src/lib/elliottEngineV2/impulse.ts", note: "`ld_r3_w5_ge_1382_w4`" },
    ],
  },
  {
    id: "diagonal_subwave_composition_nested_heuristic",
    status: "aligned",
    title: "Diagonal: nested subwave proofs (bounded heuristic scope)",
    summary:
      "Leading vs ending paths use distinct check ids; implementation is best-effort micro-zigzag search — documented as engine scope, not manual chart audit.",
    theory: "Ending 3-3-3-3-3 vs leading 5-3-5-3-5 at lower degree.",
    code: "`addDiagonalSubwaveProof` in `engine.ts`.",
    impact: "Matches product scope: automated evidence within pivot/window limits.",
    references: [
      { file: "web/src/lib/elliottEngineV2/engine.ts", note: "`addDiagonalSubwaveProof`" },
      { file: "web/src/lib/elliottEngineV2/corrective.ts", note: "`detectNestedAbcCorrectiveInLeg`" },
    ],
  },
  {
    id: "triangle_internal_three_nested_heuristic",
    status: "aligned",
    title: "Triangle: A–E nested corrective proofs (bounded heuristic scope)",
    summary:
      "`tri_*_corrective3` gates `confirmed`; legs use `detectNestedCorrectiveInLeg` within the same pivot-depth limits as other nested proofs.",
    theory: "3-3-3-3-3 structure is approximated by automated corrective detection on each leg.",
    code: "`addTriangleLegProof` in `engine.ts`.",
    impact: "Documented as heuristic scope rather than hand-counted subwaves.",
    references: [{ file: "web/src/lib/elliottEngineV2/engine.ts", note: "`addTriangleLegProof`" }],
  },
  {
    id: "diagonal_menu_default_off",
    status: "aligned",
    title: "Diagonal motive enabled in pattern menu by default",
    summary: "`DEFAULT_ELLIOTT_PATTERN_MENU.motive_diagonal` is true so diagonal scans run unless the user disables them.",
    theory: "Diagonals are first-class motive variants in scope.",
    code: "`elliottPatternMenuCatalog.ts`.",
    impact: "Diagonal support is discoverable without toggling the menu.",
    references: [{ file: "web/src/lib/elliottPatternMenuCatalog.ts", note: "`motive_diagonal` default" }],
  },
  {
    id: "flat_regular_vs_expanded_not_encoded",
    status: "aligned",
    title: "Flat: expanded vs regular band encoded as check ids",
    summary: "`flat_ba_variant_expanded` passes when B/A ≥ 1.0; otherwise the detail describes the regular band (B/A ≥ 0.9).",
    theory: "Expanded vs regular flats are commonly separated by whether B retraces beyond A’s origin.",
    code: "`buildTez254AbcChecks` for `pattern === \"flat\"` in `tezWaveChecks.ts`.",
    impact: "UI and drift can read subtype hints from checks.",
    references: [{ file: "web/src/lib/elliottEngineV2/tezWaveChecks.ts", note: "`flat_ba_variant_expanded`" }],
  },
  {
    id: "zigzag_ac_nested_motive_heuristic",
    status: "aligned",
    title: "Zigzag: A/C nested motive checks (bounded heuristic scope)",
    summary:
      "`zz_a_motive5` / `zz_c_motive5` gate `confirmed` using automated nested impulse detection — same practical limits as other nested features.",
    theory: "Zigzag 5-3-5 at the next lower degree.",
    code: "`addZigzagMotiveProof` and `correctiveIsConfirmed` in `engine.ts`.",
    impact: "Aligned with engine scope: automated evidence, not exhaustive manual subdivision.",
    references: [{ file: "web/src/lib/elliottEngineV2/engine.ts", note: "`addZigzagMotiveProof`" }],
  },
  {
    id: "flat_nested_abc_heuristic",
    status: "aligned",
    title: "Flat: A/B/C nested proofs (bounded heuristic scope)",
    summary:
      "`flat_a_corrective3`, `flat_b_corrective3`, `flat_c_motive5` gate `confirmed` via micro zigzag nested searches with documented detector limits.",
    theory: "Flat 3-3-5 at the next lower degree.",
    code: "`addFlatStructureProof` in `engine.ts`.",
    impact: "Automated structural evidence within pivot depth and windowing — documented scope.",
    references: [{ file: "web/src/lib/elliottEngineV2/engine.ts", note: "`addFlatStructureProof`" }],
  },
  {
    id: "diagonal_role_mtf_parent_v1",
    status: "aligned",
    title: "Diagonal: MTF parent W1/W5 time overlap refines role (v1)",
    summary:
      "After all timeframes run, `applyMtfDiagonalRefinement` compares the micro diagonal epoch span to parent wave-1 vs wave-5 spans (`diagonalMtf.ts`). `15m` uses `1h` then `4h`; `1h` uses `4h`. Rebuilds nested diagonal proofs when MTF picks `leading` vs `ending`.",
    theory: "Leading vs ending placement relative to parent motive W1 vs W5 (time overlap heuristic).",
    code: "`pickMtfDiagonalRoleForMicroTf` / `pickMtfDiagonalRoleFor1hTf` + `buildDiagonalSubwaveProof` override + `ImpulseCountV2.diagonalRoleSource`.",
    impact: "Still heuristic (parent count may be wrong); corrective C-leg ending diagonals are out of scope for v1.",
    references: [
      { file: "web/src/lib/elliottEngineV2/diagonalMtf.ts", note: "overlap thresholds" },
      { file: "web/src/lib/elliottEngineV2/engine.ts", note: "`applyMtfDiagonalRefinement`" },
    ],
  },
] as const;

const PARTIAL: readonly ElliottTheoryCodeFinding[] = [
] as const;

const MISSING: readonly ElliottTheoryCodeFinding[] = [
] as const;

/**
 * Inventory: 41 aligned · 0 partial · 0 missing (= 41).
 */
export const ELLIOTT_THEORY_CODE_FINDINGS: readonly ElliottTheoryCodeFinding[] = [
  ...ALIGNED,
  ...PARTIAL,
  ...MISSING,
] as const;

