-- Faz 9.8.13 — system identity + live_positions dry-insert enablement.
--
-- live_positions requires org_id + user_id NOT NULL. Dry-mode rows are
-- machine-generated by the execution bridge, so we seed a dedicated
-- `system` organisation + user and stash their UUIDs in system_config
-- for cheap lookup from Rust (no join required on the hot path).

-- Seed a system organisation. gen_random_uuid on conflict-do-nothing
-- would churn UUIDs on re-runs; we resolve the existing row instead.
DO $$
DECLARE
    v_org_id  UUID;
    v_user_id UUID;
BEGIN
    SELECT id INTO v_org_id FROM organizations WHERE name = 'system';
    IF v_org_id IS NULL THEN
        INSERT INTO organizations (name) VALUES ('system') RETURNING id INTO v_org_id;
    END IF;

    SELECT id INTO v_user_id FROM users WHERE email = 'system@qtss.local';
    IF v_user_id IS NULL THEN
        INSERT INTO users (org_id, email, password_hash, display_name, is_admin)
        VALUES (v_org_id, 'system@qtss.local',
                '!disabled', 'QTSS System', FALSE)
        RETURNING id INTO v_user_id;
    END IF;

    -- Upsert into system_config so the worker can resolve by config_key.
    INSERT INTO system_config
        (module, config_key, value, schema_version, description, is_secret)
    VALUES
        ('execution', 'dry.default_org_id',
         to_jsonb(v_org_id::text), 1,
         'UUID of the seed "system" organisation used for dry-mode live_positions rows.',
         FALSE)
    ON CONFLICT (module, config_key) DO UPDATE
        SET value = EXCLUDED.value;

    INSERT INTO system_config
        (module, config_key, value, schema_version, description, is_secret)
    VALUES
        ('execution', 'dry.default_user_id',
         to_jsonb(v_user_id::text), 1,
         'UUID of the seed "system" user used for dry-mode live_positions rows.',
         FALSE)
    ON CONFLICT (module, config_key) DO UPDATE
        SET value = EXCLUDED.value;
END $$;
