-- 0184_elliott_duplicate_purge.sql
--
-- NO-OP. Asıl 35M+ satır DELETE'i sqlx auto-migration içinde yapmak
-- worker başlangıcında uzun transaction + row lock oluşturup login'i
-- bloke ediyordu (pg_stat_activity gözleminde birden fazla paralel
-- 0184 retry + REFRESH MATERIALIZED VIEW ile deadlock'a yaklaştı).
--
-- Bu migration artık yalnızca sqlx'in kaydını koymak için boş bir
-- pas. Gerçek duplike temizliği `scripts/purge_detections_duplicates.sh`
-- (batch'li DELETE) aracılığıyla off-peak'de manuel koşulur.
-- Regresyon guard'ı olan partial UNIQUE index ise 0185'te, duplikeler
-- temizlendikten sonra kurulur.
SELECT 1;
