//! Loss / outcome attribution.
//!
//! User spec: "backtestte oluşacak zararların sebeplerini de daha
//! sonra detaylı analiz etmeni isteyeceğim". Every closed trade gets
//! a structured `OutcomeAttribution` so the operator can ask:
//!
//!   - "How many of my losers stopped out vs timed out?"
//!   - "Which component score was weakest on the losing trades?"
//!   - "Were there counter-evidence signals at entry I missed?"
//!   - "What was the median MFE on losers — did they ever profit?"
//!
//! This module operates on closed `IqTrade` records and returns a
//! standalone attribution that gets serialised alongside the trade
//! in the JSONL log + report.

use serde::{Deserialize, Serialize};

use super::trade::{IqTrade, TradeOutcome, TradeState};

/// Top-level outcome bucket — wins vs losses vs aborted. Keep this
/// small (and stable) so reports can pivot on it without tripping
/// over enum variants. `LossReason` does the fine-grained slicing
/// of losses.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OutcomeClass {
    /// Net PnL > 0 after costs.
    Win,
    /// Net PnL < 0 after costs.
    Loss,
    /// Net PnL ≈ 0 (within ±0.05% — slippage / fee noise).
    Scratch,
    /// Never opened (entry slippage too high, etc.).
    Aborted,
    /// Trade is still open at the end of the backtest window.
    OpenAtEnd,
}

/// Why did the trade lose? Granular categories — when a trade is
/// classified `OutcomeClass::Loss`, exactly one `LossReason` fits.
/// Wins / scratches / aborts get `None`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LossReason {
    /// Stop loss hit before any TP — straight-up wrong direction.
    StopLossNoTp,
    /// Hit at least one TP but stopped out before the planned final
    /// TP. Salvageable PnL but worse than expected.
    StopLossAfterPartialTp,
    /// Trailing stop hit AFTER the trade went favourable (would-be
    /// profit walked back). Often a "should have taken profit" miss.
    TrailingStopAfterMfe,
    /// Held for `max_holding_bars` and never reached TP nor SL —
    /// market chopped, position bled costs.
    TimeoutNoProgress,
    /// Held past max with negative PnL when forced exit fired.
    TimeoutNegative,
    /// External signal flipped against the position
    /// (e.g. UTAD / SOW / Wyckoff invalidation event mid-trade).
    InvalidationEvent,
    /// MFE was MORE than the SL distance — the trade WAS profitable
    /// at one point but never hit a TP. Indicates TP placement may
    /// be too aggressive.
    MfeBeyondSlButNoTp,
    /// PnL is barely negative; the cost model alone explains the
    /// loss (fees + slippage + funding > realised price move).
    /// Strategic signal: a "scratch" that fell into red because of
    /// costs, not signal failure.
    CostsOnly,
}

/// Path-level diagnostic — how did the price move WHILE the trade
/// was open? Captures the asymmetry between favourable and adverse
/// excursions so we can call out trades that "should have been
/// taken off earlier".
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct PathDiagnostic {
    pub max_favorable_pct: f64,
    pub max_adverse_pct: f64,
    pub bars_held: u32,
    pub bars_to_first_tp: Option<u32>,
    pub bars_to_max_favorable: Option<u32>,
    /// Reward:risk realised — `mfe / |mae|`. > 1 means the position
    /// had more upside than downside even if it closed red.
    pub realised_rr: f64,
}

/// Component-score weakness — which channel had the lowest score at
/// entry. For losing trades, a consistent "weakest = X" pattern
/// suggests X's threshold is too lax. Used by the optimisation
/// module to bias weight grids.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ComponentDiagnostic {
    pub weakest_channel: Option<String>,
    pub weakest_score: f64,
    pub strongest_channel: Option<String>,
    pub strongest_score: f64,
    /// All 10 component values flattened — convenience for SQL
    /// queries / pandas pivots downstream.
    pub all_scores: serde_json::Value,
}

/// Final attribution record — embedded in the trade log next to
/// the raw `IqTrade`. Designed to answer a fixed set of analyst
/// questions WITHOUT rerunning the backtest.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OutcomeAttribution {
    pub class: OutcomeClass,
    pub loss_reason: Option<LossReason>,
    pub path: PathDiagnostic,
    pub components: ComponentDiagnostic,
    /// Free-form narrative ("Stopped out 3 bars before W3 broke
    /// north — Wyckoff Spring confluent setup, weakest channel was
    /// fib_retrace at 0.30."). Generated by the classifier as a
    /// human-readable summary.
    pub narrative: String,
}

/// Threshold below which `net_pnl_pct` counts as a "scratch" rather
/// than a loss / win. Default 0.05% (5 basis points) — anything
/// inside is fee + slippage noise.
///
/// `net_pnl_pct` is stored in PERCENT (e.g. 1.5 = 1.5%), so we keep
/// the threshold in the same unit and compare directly.
const DEFAULT_SCRATCH_PCT: f64 = 0.05;

/// Classify a closed (or open-at-end) trade. Pure function — no IO,
/// safe to call in tight loops over thousands of trades.
pub fn classify(trade: &IqTrade) -> OutcomeAttribution {
    classify_with_threshold(trade, DEFAULT_SCRATCH_PCT)
}

pub fn classify_with_threshold(
    trade: &IqTrade,
    scratch_threshold_pct: f64,
) -> OutcomeAttribution {
    let class = if trade.state == TradeState::Aborted {
        OutcomeClass::Aborted
    } else if trade.state != TradeState::Closed {
        OutcomeClass::OpenAtEnd
    } else if trade.net_pnl_pct.abs() < scratch_threshold_pct {
        OutcomeClass::Scratch
    } else if trade.net_pnl_pct > 0.0 {
        OutcomeClass::Win
    } else {
        OutcomeClass::Loss
    };

    let loss_reason = if class == OutcomeClass::Loss {
        Some(infer_loss_reason(trade))
    } else {
        None
    };

    let path = path_diagnostic(trade);
    let components = component_diagnostic(trade);
    let narrative = render_narrative(class, loss_reason, &path, &components);
    OutcomeAttribution {
        class,
        loss_reason,
        path,
        components,
        narrative,
    }
}

fn infer_loss_reason(t: &IqTrade) -> LossReason {
    use TradeOutcome::*;
    let outcome = t.outcome.unwrap_or(StopLoss);
    let mfe = t.max_favorable_pct;
    let mae = t.max_adverse_pct.abs();

    match outcome {
        TakeProfitFull | TakeProfitPartial => {
            // Closed with TP but net_pnl_pct < 0 ⇒ costs dominated.
            LossReason::CostsOnly
        }
        StopLoss => {
            // Did the trade ever hit a TP before being stopped?
            let any_tier_realised = t
                .tier_pnls
                .iter()
                .take(t.take_profits.len())
                .any(|p| *p > rust_decimal::Decimal::ZERO);
            if any_tier_realised {
                LossReason::StopLossAfterPartialTp
            } else if mfe > mae && mae > 0.0 {
                // We DID see profit but didn't take it; SL hit later.
                LossReason::MfeBeyondSlButNoTp
            } else {
                LossReason::StopLossNoTp
            }
        }
        TrailingStop => LossReason::TrailingStopAfterMfe,
        Timeout => {
            if t.net_pnl_pct < -0.5 {
                LossReason::TimeoutNegative
            } else {
                LossReason::TimeoutNoProgress
            }
        }
        Invalidated => LossReason::InvalidationEvent,
        Aborted => LossReason::CostsOnly, // shouldn't happen — Aborted class
    }
}

fn path_diagnostic(t: &IqTrade) -> PathDiagnostic {
    let mfe = t.max_favorable_pct;
    let mae = t.max_adverse_pct.abs();
    let realised_rr = if mae > 0.0 { mfe / mae } else { mfe };
    // First snapshot crossing TP1's threshold, if any. v1 uses the
    // simple "any positive snapshot ≥ 50% of the smallest TP" rule;
    // a smarter version ties to `take_profits[0]` price exactly —
    // FAZ 26.5 once the runner emits per-TP fill snapshots.
    let bars_to_first_tp = t
        .snapshots
        .iter()
        .find(|s| s.unrealised_pnl_pct >= 0.5)
        .map(|s| s.bars_held);
    let bars_to_max_favorable = t
        .snapshots
        .iter()
        .find(|s| (s.unrealised_pnl_pct - mfe).abs() < 0.001)
        .map(|s| s.bars_held);
    PathDiagnostic {
        max_favorable_pct: mfe,
        max_adverse_pct: t.max_adverse_pct,
        bars_held: t.bars_held,
        bars_to_first_tp,
        bars_to_max_favorable,
        realised_rr,
    }
}

fn component_diagnostic(t: &IqTrade) -> ComponentDiagnostic {
    let mut weakest_channel: Option<String> = None;
    let mut weakest_score = f64::INFINITY;
    let mut strongest_channel: Option<String> = None;
    let mut strongest_score = f64::NEG_INFINITY;
    if let Some(obj) = t.entry_components.as_object() {
        for (key, val) in obj {
            // Skip nested meta blobs (wyckoff_event, cycle_context).
            let Some(score) = val.as_f64() else { continue };
            if score < weakest_score {
                weakest_score = score;
                weakest_channel = Some(key.clone());
            }
            if score > strongest_score {
                strongest_score = score;
                strongest_channel = Some(key.clone());
            }
        }
    }
    if !weakest_score.is_finite() {
        weakest_score = 0.0;
    }
    if !strongest_score.is_finite() {
        strongest_score = 0.0;
    }
    ComponentDiagnostic {
        weakest_channel,
        weakest_score,
        strongest_channel,
        strongest_score,
        all_scores: t.entry_components.clone(),
    }
}

fn render_narrative(
    class: OutcomeClass,
    reason: Option<LossReason>,
    path: &PathDiagnostic,
    comp: &ComponentDiagnostic,
) -> String {
    let class_str = match class {
        OutcomeClass::Win => "WIN",
        OutcomeClass::Loss => "LOSS",
        OutcomeClass::Scratch => "SCRATCH",
        OutcomeClass::Aborted => "ABORTED",
        OutcomeClass::OpenAtEnd => "OPEN_AT_END",
    };
    let reason_str = reason.map(|r| format!("{r:?}")).unwrap_or_default();
    let weakest = comp.weakest_channel.as_deref().unwrap_or("?");
    let strongest = comp.strongest_channel.as_deref().unwrap_or("?");
    format!(
        "{} {} | held={} bars | mfe={:.2}% mae={:.2}% rr={:.2} | weakest={}({:.2}) strongest={}({:.2})",
        class_str,
        reason_str,
        path.bars_held,
        path.max_favorable_pct,
        path.max_adverse_pct,
        path.realised_rr,
        weakest,
        comp.weakest_score,
        strongest,
        comp.strongest_score,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::iq::config::IqPolarity;
    use chrono::Utc;
    use rust_decimal_macros::dec;
    use serde_json::json;

    fn closed_loser(outcome: TradeOutcome, mfe: f64, mae: f64) -> IqTrade {
        let mut t = IqTrade::pending(
            "test",
            IqPolarity::Dip,
            "BTCUSDT",
            "4h",
            "binance",
            "futures",
            100,
            Utc::now(),
            dec!(50000),
            dec!(48000),
            vec![dec!(52000)],
            dec!(0.1),
            json!({
                "structural_completion": 0.7,
                "fib_retrace_quality":   0.3,
                "wyckoff_alignment":     0.85,
                "cycle_alignment":       0.6,
            }),
            0.65,
        );
        t.state = TradeState::Closed;
        t.outcome = Some(outcome);
        t.max_favorable_pct = mfe;
        t.max_adverse_pct = mae;
        t.net_pnl_pct = -0.5;
        t.bars_held = 30;
        t
    }

    #[test]
    fn straight_stop_classifies_as_no_tp() {
        let t = closed_loser(TradeOutcome::StopLoss, 0.2, -1.0);
        let attr = classify(&t);
        assert_eq!(attr.class, OutcomeClass::Loss);
        assert_eq!(attr.loss_reason, Some(LossReason::StopLossNoTp));
    }

    #[test]
    fn mfe_beyond_sl_no_tp_caught() {
        let t = closed_loser(TradeOutcome::StopLoss, 2.5, -1.0);
        let attr = classify(&t);
        assert_eq!(attr.loss_reason, Some(LossReason::MfeBeyondSlButNoTp));
    }

    #[test]
    fn timeout_negative_caught() {
        let t = closed_loser(TradeOutcome::Timeout, 0.1, -0.6);
        let attr = classify(&t);
        // -0.5 net_pnl_pct, |val|=0.5; threshold > 0.5 means
        // TimeoutNegative requires net_pnl_pct < -0.5. Set
        // threshold tighter for the test.
        let attr = classify_with_threshold(&t, 0.0001);
        assert!(matches!(
            attr.loss_reason,
            Some(LossReason::TimeoutNoProgress) | Some(LossReason::TimeoutNegative)
        ));
    }

    #[test]
    fn weakest_channel_identified() {
        let t = closed_loser(TradeOutcome::StopLoss, 0.1, -1.0);
        let attr = classify(&t);
        assert_eq!(attr.components.weakest_channel.as_deref(), Some("fib_retrace_quality"));
        assert!(attr.components.weakest_score < 0.4);
    }

    #[test]
    fn scratch_classified_when_pnl_near_zero() {
        let mut t = closed_loser(TradeOutcome::StopLoss, 0.0, 0.0);
        t.net_pnl_pct = 0.001; // 0.1 bps
        let attr = classify(&t);
        assert_eq!(attr.class, OutcomeClass::Scratch);
        assert!(attr.loss_reason.is_none());
    }
}
